version: '3'
services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 15432:5432
    volumes:
      - ./entrypoint:/docker-entrypoint-initdb.d
